#load Bionano source code in the same directory as this example file
source('bionano.R')

#set path to XMAP files, the script assumes that CMAP files for reference and query are in the same foler (aln.xmap, aln_q.cmap, aln_r.cmap)

f <- '/path/to/aln.xmap'

#path to key file with scaffold names as generated by the fa2cmap_multi_color.pl script of Bionano solve
k <- 'scaffolds_DLE1_0kb_0labels_key.txt'

#prefix for optical contigs
p <- 'opt_contig'

#read alignments
read_aln(xmap_file=f, key_file=k, prefix=p) -> aln
#get coverage statistics, consider only alignment with a minimum confidence score of 20 and sequence scaffolds / optical contigs >= 100 kb
# cov_ref/cov_qry is the proportion of reference/query labels sites that are by an alignment, but the sites need not be aligned themselves
# aln_ref/aln_qry is the propostion of label sites aligned (at least one; multiple alignment are allowed and counted only once)
get_cov_stats(aln, confidence=20, min.length=1e5)
